// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthChallenge struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	AuthTransactionID *uuid.UUID         `db:"auth_transaction_id" json:"auth_transaction_id"`
	Identifier        string             `db:"identifier" json:"identifier"`
	SecretHash        string             `db:"secret_hash" json:"secret_hash"`
	Purpose           string             `db:"purpose" json:"purpose"`
	State             []byte             `db:"state" json:"state"`
	Attempts          int32              `db:"attempts" json:"attempts"`
	MaxAttempts       int32              `db:"max_attempts" json:"max_attempts"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthTransaction struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Identifier     string             `db:"identifier" json:"identifier"`
	UserID         *uuid.UUID         `db:"user_id" json:"user_id"`
	State          string             `db:"state" json:"state"`
	SelectedMethod *string            `db:"selected_method" json:"selected_method"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OutboxEvent struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Subject          string             `db:"subject" json:"subject"`
	AggregateType    string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID      uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	Payload          []byte             `db:"payload" json:"payload"`
	Headers          []byte             `db:"headers" json:"headers"`
	AvailableAt      pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Attempts         int32              `db:"attempts" json:"attempts"`
	PublishFailures  int32              `db:"publish_failures" json:"publish_failures"`
	RedriveCount     int32              `db:"redrive_count" json:"redrive_count"`
	LastError        *string            `db:"last_error" json:"last_error"`
	QuarantinedAt    pgtype.Timestamptz `db:"quarantined_at" json:"quarantined_at"`
	QuarantineCode   *string            `db:"quarantine_code" json:"quarantine_code"`
	QuarantineReason *string            `db:"quarantine_reason" json:"quarantine_reason"`
	LockedAt         pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy         *string            `db:"locked_by" json:"locked_by"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PersonalAccessToken struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Scopes      []string           `db:"scopes" json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Sandbox struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	VmID           string             `db:"vm_id" json:"vm_id"`
	Template       string             `db:"template" json:"template"`
	Status         string             `db:"status" json:"status"`
	Vcpu           int32              `db:"vcpu" json:"vcpu"`
	MemoryMb       int32              `db:"memory_mb" json:"memory_mb"`
	TimeoutSeconds int32              `db:"timeout_seconds" json:"timeout_seconds"`
	AllowedHosts   []string           `db:"allowed_hosts" json:"allowed_hosts"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt      pgtype.Timestamptz `db:"started_at" json:"started_at"`
	StoppedAt      pgtype.Timestamptz `db:"stopped_at" json:"stopped_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent  *string            `db:"user_agent" json:"user_agent"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Name          *string            `db:"name" json:"name"`
	PasswordHash  *string            `db:"password_hash" json:"password_hash"`
	DisabledAt    pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
