// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (
    user_id,
    provider,
    provider_uid
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, provider, provider_uid, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Provider    string    `db:"provider" json:"provider"`
	ProviderUid string    `db:"provider_uid" json:"provider_uid"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderUid)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :exec
DELETE FROM oauth_accounts
WHERE id = $1
  AND user_id = $2
`

type DeleteOAuthAccountParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteOAuthAccount(ctx context.Context, arg DeleteOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthAccount, arg.ID, arg.UserID)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_uid, created_at, updated_at
FROM oauth_accounts
WHERE provider = $1
  AND provider_uid = $2
LIMIT 1
`

type GetOAuthAccountParams struct {
	Provider    string `db:"provider" json:"provider"`
	ProviderUid string `db:"provider_uid" json:"provider_uid"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderUid)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountByID = `-- name: GetOAuthAccountByID :one
SELECT id, user_id, provider, provider_uid, created_at, updated_at
FROM oauth_accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOAuthAccountByID(ctx context.Context, id uuid.UUID) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByID, id)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOAuthAccount = `-- name: GetUserOAuthAccount :one
SELECT id, user_id, provider, provider_uid, created_at, updated_at
FROM oauth_accounts
WHERE user_id = $1
  AND provider = $2
LIMIT 1
`

type GetUserOAuthAccountParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	Provider string    `db:"provider" json:"provider"`
}

func (q *Queries) GetUserOAuthAccount(ctx context.Context, arg GetUserOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getUserOAuthAccount, arg.UserID, arg.Provider)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthAccountsByUserID = `-- name: ListOAuthAccountsByUserID :many
SELECT id, user_id, provider, provider_uid, created_at, updated_at
FROM oauth_accounts
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, listOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthAccount = `-- name: UpdateOAuthAccount :one
UPDATE oauth_accounts
SET
    provider_uid = $1,
    updated_at = NOW()
WHERE id = $2
  AND user_id = $3
RETURNING id, user_id, provider, provider_uid, created_at, updated_at
`

type UpdateOAuthAccountParams struct {
	ProviderUid string    `db:"provider_uid" json:"provider_uid"`
	ID          uuid.UUID `db:"id" json:"id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateOAuthAccount(ctx context.Context, arg UpdateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, updateOAuthAccount, arg.ProviderUid, arg.ID, arg.UserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
