// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_access_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO personal_access_tokens (
    user_id,
    name,
    token_hash,
    token_prefix,
    scopes,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_at
`

type CreateTokenParams struct {
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Scopes      []string           `db:"scopes" json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_at
FROM personal_access_tokens
WHERE token_hash = $1
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, name, token_prefix, scopes, expires_at, last_used_at, created_at
FROM personal_access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListTokensByUserRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Scopes      []string           `db:"scopes" json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListTokensByUser(ctx context.Context, userID uuid.UUID) ([]ListTokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokensByUserRow{}
	for rows.Next() {
		var i ListTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :exec
DELETE FROM personal_access_tokens
WHERE id = $1
  AND user_id = $2
`

type RevokeTokenParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.Exec(ctx, revokeToken, arg.ID, arg.UserID)
	return err
}

const touchToken = `-- name: TouchToken :exec
UPDATE personal_access_tokens
SET last_used_at = NOW()
WHERE last_used_at IS NULL
   OR last_used_at < NOW() - INTERVAL '1 minute'
`

func (q *Queries) TouchToken(ctx context.Context) error {
	_, err := q.db.Exec(ctx, touchToken)
	return err
}
