// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandboxes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (
    user_id,
    vm_id,
    template,
    vcpu,
    memory_mb,
    timeout_seconds,
    allowed_hosts,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at, updated_at
`

type CreateSandboxParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	VmID           string    `db:"vm_id" json:"vm_id"`
	Template       string    `db:"template" json:"template"`
	Vcpu           int32     `db:"vcpu" json:"vcpu"`
	MemoryMb       int32     `db:"memory_mb" json:"memory_mb"`
	TimeoutSeconds int32     `db:"timeout_seconds" json:"timeout_seconds"`
	AllowedHosts   []string  `db:"allowed_hosts" json:"allowed_hosts"`
	Status         *string   `db:"status" json:"status"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.UserID,
		arg.VmID,
		arg.Template,
		arg.Vcpu,
		arg.MemoryMb,
		arg.TimeoutSeconds,
		arg.AllowedHosts,
		arg.Status,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VmID,
		&i.Template,
		&i.Status,
		&i.Vcpu,
		&i.MemoryMb,
		&i.TimeoutSeconds,
		&i.AllowedHosts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSandbox = `-- name: DeleteSandbox :exec
DELETE FROM sandboxes WHERE id = $1
`

func (q *Queries) DeleteSandbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSandbox, id)
	return err
}

const findStuckSandboxes = `-- name: FindStuckSandboxes :many
SELECT id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at, updated_at FROM sandboxes
WHERE status = $1
  AND created_at < NOW() - ($2::text || ' seconds')::interval
ORDER BY created_at ASC
`

type FindStuckSandboxesParams struct {
	Status        string `db:"status" json:"status"`
	MaxAgeSeconds string `db:"max_age_seconds" json:"max_age_seconds"`
}

func (q *Queries) FindStuckSandboxes(ctx context.Context, arg FindStuckSandboxesParams) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, findStuckSandboxes, arg.Status, arg.MaxAgeSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VmID,
			&i.Template,
			&i.Status,
			&i.Vcpu,
			&i.MemoryMb,
			&i.TimeoutSeconds,
			&i.AllowedHosts,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSandboxByID = `-- name: GetSandboxByID :one
SELECT id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at, updated_at FROM sandboxes
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSandboxByID(ctx context.Context, id uuid.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByID, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VmID,
		&i.Template,
		&i.Status,
		&i.Vcpu,
		&i.MemoryMb,
		&i.TimeoutSeconds,
		&i.AllowedHosts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSandboxByVMID = `-- name: GetSandboxByVMID :one
SELECT id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at, updated_at FROM sandboxes
WHERE vm_id = $1
LIMIT 1
`

func (q *Queries) GetSandboxByVMID(ctx context.Context, vmID string) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByVMID, vmID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VmID,
		&i.Template,
		&i.Status,
		&i.Vcpu,
		&i.MemoryMb,
		&i.TimeoutSeconds,
		&i.AllowedHosts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSandboxesByUser = `-- name: ListSandboxesByUser :many
SELECT id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at, updated_at FROM sandboxes
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByUser(ctx context.Context, userID uuid.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VmID,
			&i.Template,
			&i.Status,
			&i.Vcpu,
			&i.MemoryMb,
			&i.TimeoutSeconds,
			&i.AllowedHosts,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSandboxStatus = `-- name: UpdateSandboxStatus :one
UPDATE sandboxes
SET
    status = $1,
    started_at = CASE WHEN $1 = 'running' THEN NOW() ELSE started_at END,
    stopped_at = CASE WHEN $1 IN ('stopped', 'failed', 'cleanup_failed') THEN NOW() ELSE stopped_at END
WHERE id = $2
RETURNING id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at, updated_at
`

type UpdateSandboxStatusParams struct {
	Status string    `db:"status" json:"status"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateSandboxStatus(ctx context.Context, arg UpdateSandboxStatusParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, updateSandboxStatus, arg.Status, arg.ID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VmID,
		&i.Template,
		&i.Status,
		&i.Vcpu,
		&i.MemoryMb,
		&i.TimeoutSeconds,
		&i.AllowedHosts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.UpdatedAt,
	)
	return i, err
}
