// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandboxs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (
    user_id,
    vm_id,
    template,
    vcpu,
    memory_mb,
    timeout_seconds,
    allowed_hosts,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at
`

type CreateSandboxParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	VmID           string    `db:"vm_id" json:"vm_id"`
	Template       string    `db:"template" json:"template"`
	Vcpu           int32     `db:"vcpu" json:"vcpu"`
	MemoryMb       int32     `db:"memory_mb" json:"memory_mb"`
	TimeoutSeconds int32     `db:"timeout_seconds" json:"timeout_seconds"`
	AllowedHosts   []string  `db:"allowed_hosts" json:"allowed_hosts"`
	Status         *string   `db:"status" json:"status"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.UserID,
		arg.VmID,
		arg.Template,
		arg.Vcpu,
		arg.MemoryMb,
		arg.TimeoutSeconds,
		arg.AllowedHosts,
		arg.Status,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VmID,
		&i.Template,
		&i.Status,
		&i.Vcpu,
		&i.MemoryMb,
		&i.TimeoutSeconds,
		&i.AllowedHosts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
	)
	return i, err
}

const getSandboxByID = `-- name: GetSandboxByID :one
SELECT id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at FROM sandboxes
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSandboxByID(ctx context.Context, id uuid.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByID, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VmID,
		&i.Template,
		&i.Status,
		&i.Vcpu,
		&i.MemoryMb,
		&i.TimeoutSeconds,
		&i.AllowedHosts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
	)
	return i, err
}

const getSandboxByVMID = `-- name: GetSandboxByVMID :one
SELECT id, user_id, vm_id, template, status, vcpu, memory_mb, timeout_seconds, allowed_hosts, created_at, started_at, stopped_at FROM sandboxes
WHERE vm_id = $1
LIMIT 1
`

func (q *Queries) GetSandboxByVMID(ctx context.Context, vmID string) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByVMID, vmID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VmID,
		&i.Template,
		&i.Status,
		&i.Vcpu,
		&i.MemoryMb,
		&i.TimeoutSeconds,
		&i.AllowedHosts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
	)
	return i, err
}
