// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    token_hash,
    ip_address,
    user_agent,
    expires_at
)
SELECT
    u.id,
    $1,
    $2::inet,
    $3::text,
    $4::timestamptz
FROM users AS u
WHERE u.id = $5
  AND u.disabled_at IS NULL
RETURNING id, user_id, token_hash, ip_address, user_agent, expires_at, last_seen_at, revoked_at, created_at
`

type CreateSessionParams struct {
	TokenHash string             `db:"token_hash" json:"token_hash"`
	IpAddress *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent *string            `db:"user_agent" json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
