// Code generated by sqlc. DO NOT EDIT.
// source: team_access_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamToken = `-- name: CreateTeamToken :one
INSERT INTO team_access_tokens (team_id, name, token_hash, token_prefix, scopes, expires_at, created_by)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (
    SELECT 1 FROM team_members
    WHERE team_id = $1 AND user_id = $7 AND role IN ('owner', 'admin')
)
RETURNING id, team_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_by, created_at
`

type CreateTeamTokenParams struct {
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Scopes      []string           `db:"scopes" json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedBy   uuid.UUID          `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateTeamToken(ctx context.Context, arg CreateTeamTokenParams) (TeamAccessToken, error) {
	row := q.db.QueryRow(ctx, createTeamToken, arg.TeamID, arg.Name, arg.TokenHash, arg.TokenPrefix, arg.Scopes, arg.ExpiresAt, arg.CreatedBy)
	var i TeamAccessToken
	err := row.Scan(&i.ID, &i.TeamID, &i.Name, &i.TokenHash, &i.TokenPrefix, &i.Scopes, &i.ExpiresAt, &i.LastUsedAt, &i.CreatedBy, &i.CreatedAt)
	return i, err
}

const listTeamTokens = `-- name: ListTeamTokens :many
SELECT tat.id, tat.name, tat.token_prefix, tat.scopes, tat.expires_at, tat.last_used_at, tat.created_by, tat.created_at
FROM team_access_tokens AS tat
WHERE tat.team_id = $1
  AND EXISTS (SELECT 1 FROM team_members WHERE team_id = tat.team_id AND user_id = $2)
ORDER BY tat.created_at DESC
`

type ListTeamTokensParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type ListTeamTokensRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Scopes      []string           `db:"scopes" json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedBy   *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListTeamTokens(ctx context.Context, arg ListTeamTokensParams) ([]ListTeamTokensRow, error) {
	rows, err := q.db.Query(ctx, listTeamTokens, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamTokensRow{}
	for rows.Next() {
		var i ListTeamTokensRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TokenPrefix, &i.Scopes, &i.ExpiresAt, &i.LastUsedAt, &i.CreatedBy, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTeamToken = `-- name: RevokeTeamToken :execrows
DELETE FROM team_access_tokens AS tat
WHERE tat.id = $1 AND tat.team_id = $2
  AND EXISTS (
      SELECT 1 FROM team_members
      WHERE team_id = tat.team_id AND user_id = $3 AND role IN ('owner', 'admin')
  )
`

type RevokeTeamTokenParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeTeamToken(ctx context.Context, arg RevokeTeamTokenParams) (int64, error) {
	tag, err := q.db.Exec(ctx, revokeTeamToken, arg.ID, arg.TeamID, arg.UserID)
	return tag.RowsAffected(), err
}
